jobs:
  setup-env:
    steps:
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for setup
        run: chmod +x scripts/setup_shared.sh
      - name: Setup environment variable files
        run: ./scripts/setup_shared.sh
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew