name: Shared Module CI

on:
  push:
    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

env:
  OPENAI_API_KEY: ${{secrets.API_KEY}}

jobs:
  build-shared:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Setup environment variable files
        run: |
          chmod +x scripts/setup_shared.sh
          ./scripts/setup_shared.sh
      - name: Run a one-line script
        run: |
          chmod +x gradlew
          echo pass

  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Setup environment variable files
        run: |
          chmod +x scripts/setup_shared.sh
          ./scripts/setup_shared.sh
      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew test

  build-jvm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Setup environment variable files
        run: |
          chmod +x scripts/setup_shared.sh
          ./scripts/setup_shared.sh
      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew jvmTest

  build-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Setup environment variable files
        run: |
          chmod +x scripts/setup_shared.sh
          ./scripts/setup_shared.sh
      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew jsTest

  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Setup environment variable files
        run: |
          chmod +x scripts/setup_shared.sh
          ./scripts/setup_shared.sh
      - name: Run a one-line script
        run: |
          chmod +x gradlew
          echo pass