name: Shared Module CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  OPENAI_API_KEY: ${{ secrets.API_KEY }}

jobs:
  build-shared:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Setup environment variable files
        run: |
          chmod +x scripts/setup_shared.sh
          ./scripts/setup_shared.sh
      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew :shared:build

#  build-shared-native:
#    needs: build-shared
#    runs-on: macos-latest
#    steps:
#      - uses: actions/checkout@v3
#      - name: set up JDK 11
#        uses: actions/setup-java@v3
#        with:
#          java-version: '11'
#          distribution: 'temurin'
#          cache: gradle
#      - name: Setup environment variable files
#        run: |
#          chmod +x scripts/setup_shared.sh
#          ./scripts/setup_shared.sh
#      - name: Build with Gradle
#        run: |
#          chmod +x gradlew
#          ./gradlew build

  verify-android:
    needs: build-shared
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Setup environment variable files
        run: |
          chmod +x scripts/setup_shared.sh
          ./scripts/setup_shared.sh
      - name: Build Android App
        working-directory: android
        run: |
          ../gradlew :android:build

  verify-web:
    needs: build-shared
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: set up Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - name: Build Web App
        working-directory: web
        run: |
          ../gradlew :shared:jsNodeDevelopmentLibraryDistribution
          npm run build
          npm run test
          

#  verify-ios:
#    needs: build-shared-native
#    runs-on: macos-latest
#    defaults:
#      run:
#        working-directory: ios
#    steps:
#      - uses: actions/checkout@v3
#      - name: set up JDK 11
#        uses: actions/setup-java@v3
#        with:
#          java-version: '11'
#          distribution: 'temurin'
#          cache: gradle
#      - name: Setup environment variable files
#        run: |
#          chmod +x scripts/setup_shared.sh
#          ./scripts/setup_shared.sh
#      - name: Run a one-line script
#        run: |
#          chmod +x gradlew
#          echo pass