name: Shared Module CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  OPENAI_API_KEY: ${{secrets.API_KEY}}

jobs:
  build-shared:
    runs-on: macos-latest
    uses: ./.github/workflows/common.yml
    steps:
      - name: Run a one-line script
        run: echo pass

  build-android:
    runs-on: ubuntu-latest
    uses: ./.github/workflows/common.yml
    steps:
      - name: Build with Gradle
        run: ./gradlew :android:build

  build-web:
    runs-on: ubuntu-latest
    uses: ./.github/workflows/common.yml
    steps:
      - name: Build with Gradle
        run: ./gradlew jsBrowserDistribution

  build-ios:
    runs-on: macos-latest
    steps:
      - name: Run a one-line script
        run: echo pass