name: Shared Module CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  OPENAI_API_KEY: ${{ secrets.API_KEY }}

jobs:
  build-shared:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Setup environment variable files
        run: |
          chmod +x scripts/setup_shared.sh
          ./scripts/setup_shared.sh
      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew build
      - name: Compress Output
        run: |
          tar -zcvf build-shared.tar.gz build
      - name: 'Upload build-shared Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: build-shared
          path: build-shared.tar.gz

  build-shared-native:
    needs: build-shared
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Download build zip from build-shared
        uses: actions/download-artifact@v3
        with:
          name: build-shared
      - name: Unzip build folder
        run: unzip build-shared.tar.gz
      - name: Setup environment variable files
        run: |
          chmod +x scripts/setup_shared.sh
          ./scripts/setup_shared.sh
      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew build
      - name: Compress Output
        run: |
          tar -zcvf build-shared-native.tar.gz build
      - name: 'Upload build-shared-native Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: build-shared-native
          path: build-shared-native.tar.gz

  verify-android:
    needs: build-shared-native
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Download build zip from build-shared-native
        uses: actions/download-artifact@v3
        with:
          name: build-shared-native
      - name: Unzip build folder
        run: unzip build-shared-native.tar.gz
      - name: Setup environment variable files
        run: |
          chmod +x scripts/setup_shared.sh
          ./scripts/setup_shared.sh
      - name: Build Android App
        working-directory: android
        run: |
          ../gradlew build

  verify-web:
    needs: build-shared-native
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Download build zip from build-shared-native
        uses: actions/download-artifact@v3
        with:
          name: build-shared-native
      - name: Unzip build folder
        run: unzip build-shared-native.tar.gz
      - name: Setup environment variable files
        run: |
          chmod +x scripts/setup_shared.sh
          ./scripts/setup_shared.sh
      - name: Build Web App
        working-directory: web
        run: |
          npm run install
          npm run start
          

#  verify-ios:
#    needs: build-shared-native
#    runs-on: macos-latest
#    defaults:
#      run:
#        working-directory: ios
#    steps:
#      - uses: actions/checkout@v3
#      - name: set up JDK 11
#        uses: actions/setup-java@v3
#        with:
#          java-version: '11'
#          distribution: 'temurin'
#          cache: gradle
#      - name: Setup environment variable files
#        run: |
#          chmod +x scripts/setup_shared.sh
#          ./scripts/setup_shared.sh
#      - name: Run a one-line script
#        run: |
#          chmod +x gradlew
#          echo pass